[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_crowdfunding = "8RjcjbiGt6FxemB4mG3yHvvmnKN6yEQPiwt4a9NDtUH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
